services:
  bucket:
    build: .
    develop:
      watch:
        - action: sync
          path: ./lib
          target: /app/lib
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    volumes:
      - /srv/2bucket/files:/app/files
